<a href="https://colab.research.google.com/github/fahadpro01/Product/blob/master/Boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
days = np.array(['sun','mon','tue','wed','thu','fri','sat','mon','tue','tue'])
days

array(['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'mon', 'tue',
       'tue'], dtype='<U3')

In [4]:
data=np.random.randn(10,4)
data

array([[ 0.31015507,  0.45972609, -1.90960891, -0.50643246],
       [-0.96023904,  0.80572948,  0.19095347, -1.41798904],
       [-0.12266462,  0.78742926,  0.72793442, -0.1639578 ],
       [-0.7729685 ,  0.63356413,  0.53855549, -0.94037497],
       [ 0.1411112 , -1.056305  ,  1.2260048 , -2.10027841],
       [ 0.25886739,  0.19580011, -0.59483225,  0.02227147],
       [-1.0239779 , -0.40621577, -0.12615806, -0.65909658],
       [ 0.43871015, -0.50938643,  0.02893435, -0.16031198],
       [-0.02096476, -0.87306507, -0.50947599,  0.33635725],
       [ 1.01203446,  0.41355993, -1.0165687 ,  0.45743776]])

In [5]:
days == 'mon'

array([False,  True, False, False, False, False, False,  True, False,
       False])

In [6]:
data[days=='mon']

array([[-0.96023904,  0.80572948,  0.19095347, -1.41798904],
       [ 0.43871015, -0.50938643,  0.02893435, -0.16031198]])

In [7]:
data[days=='mon',1:]

array([[ 0.80572948,  0.19095347, -1.41798904],
       [-0.50938643,  0.02893435, -0.16031198]])

In [8]:
data[days=='mon',1]

array([ 0.80572948, -0.50938643])

In [9]:
days !='mon'

array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True])

In [12]:
~(days=='mon')

array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True])

In [14]:
data[~(days=='mon')]

array([[ 0.31015507,  0.45972609, -1.90960891, -0.50643246],
       [-0.12266462,  0.78742926,  0.72793442, -0.1639578 ],
       [-0.7729685 ,  0.63356413,  0.53855549, -0.94037497],
       [ 0.1411112 , -1.056305  ,  1.2260048 , -2.10027841],
       [ 0.25886739,  0.19580011, -0.59483225,  0.02227147],
       [-1.0239779 , -0.40621577, -0.12615806, -0.65909658],
       [-0.02096476, -0.87306507, -0.50947599,  0.33635725],
       [ 1.01203446,  0.41355993, -1.0165687 ,  0.45743776]])

In [16]:
cond=(days=='mon')
cond

array([False,  True, False, False, False, False, False,  True, False,
       False])

In [17]:
data[~cond]

array([[ 0.31015507,  0.45972609, -1.90960891, -0.50643246],
       [-0.12266462,  0.78742926,  0.72793442, -0.1639578 ],
       [-0.7729685 ,  0.63356413,  0.53855549, -0.94037497],
       [ 0.1411112 , -1.056305  ,  1.2260048 , -2.10027841],
       [ 0.25886739,  0.19580011, -0.59483225,  0.02227147],
       [-1.0239779 , -0.40621577, -0.12615806, -0.65909658],
       [-0.02096476, -0.87306507, -0.50947599,  0.33635725],
       [ 1.01203446,  0.41355993, -1.0165687 ,  0.45743776]])

In [20]:
multi_cond=(days=='mon')|(days=='Tue')
multi_cond

array([False,  True, False, False, False, False, False,  True, False,
       False])

In [21]:
data[multi_cond]

array([[-0.96023904,  0.80572948,  0.19095347, -1.41798904],
       [ 0.43871015, -0.50938643,  0.02893435, -0.16031198]])

In [22]:
data[data<0]=0
data

array([[0.31015507, 0.45972609, 0.        , 0.        ],
       [0.        , 0.80572948, 0.19095347, 0.        ],
       [0.        , 0.78742926, 0.72793442, 0.        ],
       [0.        , 0.63356413, 0.53855549, 0.        ],
       [0.1411112 , 0.        , 1.2260048 , 0.        ],
       [0.25886739, 0.19580011, 0.        , 0.02227147],
       [0.        , 0.        , 0.        , 0.        ],
       [0.43871015, 0.        , 0.02893435, 0.        ],
       [0.        , 0.        , 0.        , 0.33635725],
       [1.01203446, 0.41355993, 0.        , 0.45743776]])

In [23]:
data[days!='mon']=0.5
data

array([[0.5       , 0.5       , 0.5       , 0.5       ],
       [0.        , 0.80572948, 0.19095347, 0.        ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.43871015, 0.        , 0.02893435, 0.        ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ]])